### ISSUE TITLE
Flatpak version & Flathub publishing

### ISSUE THREAD

**Issue by Krafting** [liftoff-app/liftoff#37]
You provide linux version of your app, it would be better to also distribute your app through flatpak! and publish it on flathub!

Thank you!

**Comment by zachatrocity** [comment]
This would be awesome! Our first priority is iOS and Android. But after our 1.0 release I could look into this.

Open to contributions!

**Comment by JakobDev** [comment]
I can create a Flatpak, if you want. But building a Flutter App is Flatpak is not really possible. so the only thing I can do is repacking the prebuild Linux Binary, what means no ARM support.

**Comment by LouisMarotta** [comment]
I had made a PR for the original lemmur app https://github.com/LemmurOrg/lemmur/pull/346, I think most of it should be compatible, sadly the ARM situation seems to haven't changed since then

**Comment by zachatrocity** [comment]
That's great with me if either of you are willing to contribute and we can add a get it on flatpak badge to the readme.

**Comment by JakobDev** [comment]
I have created a Manifest:
```yaml
id: io.github.liftoff_app.liftoff
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk
command: liftoff
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --share=ipc
  - --device=dri
  - --share=network
  - --socket=pulseaudio
  - --own-name=com.liftoffapp.liftoff

modules:
  - name: liftoff
    buildsystem: simple
    build-commands:
      - mkdir -p $FLATPAK_DEST/bin
      - mkdir -p $FLATPAK_DEST/liftoff
      - cp -r * $FLATPAK_DEST/liftoff
      - ln -s $FLATPAK_DEST/liftoff/Liftoff $FLATPAK_DEST/bin/liftoff
    sources:
      - type: archive
        strip-components: 0
        only-arches: [x86_64]
        url: https://github.com/liftoff-app/liftoff/releases/download/v0.10.4/liftoff-v0.10.4-x86_64-linux.tar.gz
        sha256: 0b5a91dc1d09a2f90e761f7101c6b381f6fc8edd50f22e8e8d97eda62da0365b
        x-checker-data:
          type: json
          url: https://api.github.com/repos/liftoff-app/liftoff/releases/latest
```
It missing a Desktop Entry and a AppStream file, but I will add this with a PR.

It is also currently not available for ARM. If you can do a ARM build and publish it on GitHub, I can include it.

We got a bigger Problem here: The App says the ID is `com.liftoffapp.liftoff`, but it looks like [liftoffapp.com](https://liftoffapp.com) has nothing to do with this App. Can you clarify @zachatrocity?
